// <auto-generated />
using System;
using Gastapp_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gastapp_API.Migrations
{
    [DbContext(typeof(GastappDbContext))]
    [Migration("20260729030900_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultCategory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Gastapp.Models.CreditCard", b =>
                {
                    b.Property<string>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CutOffDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFourDigits")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Gastapp.Models.IncomeType", b =>
                {
                    b.Property<int>("IncomeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeTypeId");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            IncomeTypeId = 1,
                            IncomeTypeName = "Semanal"
                        },
                        new
                        {
                            IncomeTypeId = 2,
                            IncomeTypeName = "Quincenal"
                        },
                        new
                        {
                            IncomeTypeId = 3,
                            IncomeTypeName = "Mensual"
                        });
                });

            modelBuilder.Entity("Gastapp.Models.Spending", b =>
                {
                    b.Property<string>("SpendingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCreditCard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpendingId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("Spendings");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstPayDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentSave")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecondPayDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeekPayDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("IncomeTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.HasOne("Gastapp.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gastapp.Models.CreditCard", b =>
                {
                    b.HasOne("Gastapp.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gastapp.Models.Spending", b =>
                {
                    b.HasOne("Gastapp.Models.Category", "Category")
                        .WithMany("Spendings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastapp.Models.CreditCard", "CreditCard")
                        .WithMany("Spendings")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gastapp.Models.User", "User")
                        .WithMany("Spendings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.HasOne("Gastapp.Models.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");
                });

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("Gastapp.Models.CreditCard", b =>
                {
                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CreditCards");

                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
