// <auto-generated />
using System;
using Gastapp_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gastapp_API.Migrations
{
    [DbContext(typeof(GastappDbContext))]
    partial class GastappDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefaultCategory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Gastapp.Models.IncomeType", b =>
                {
                    b.Property<int>("IncomeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeTypeId"));

                    b.Property<string>("IncomeTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncomeTypeId");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            IncomeTypeId = 1,
                            IncomeTypeName = "Semanal"
                        },
                        new
                        {
                            IncomeTypeId = 2,
                            IncomeTypeName = "Quincenal"
                        },
                        new
                        {
                            IncomeTypeId = 3,
                            IncomeTypeName = "Mensual"
                        });
                });

            modelBuilder.Entity("Gastapp.Models.Spending", b =>
                {
                    b.Property<string>("SpendingId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpendingId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Spendings");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("FirstPayDay")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("text");

                    b.Property<decimal>("PercentSave")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<int?>("SecondPayDay")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekPayDay")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("IncomeTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.HasOne("Gastapp.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gastapp.Models.Spending", b =>
                {
                    b.HasOne("Gastapp.Models.Category", "Category")
                        .WithMany("Spendings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastapp.Models.User", "User")
                        .WithMany("Spendings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.HasOne("Gastapp.Models.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");
                });

            modelBuilder.Entity("Gastapp.Models.Category", b =>
                {
                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("Gastapp.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
